name: wavesync_client
description: Flutter client for WaveSync (mobile + web)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

platforms:
  android:
  ios:
  web:

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # WebSocket client
  web_socket_channel: ^3.0.1
  http: ^1.2.2
  audioplayers: ^5.2.1
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  flutter_web_auth_2: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
